### ISSUE TITLE
Not able to download file from Android app

### ISSUE THREAD

**Issue by cpholguera** [sensepost/objection#92]
Hi,

I'm currently testing objection together with the MSTG-Hacking-Playground app and I'm not able to download files. 

Here's the APK:

https://github.com/OWASP/MSTG-Hacking-Playground/blob/master/Android/OMTG-Android-App/app/app-arm-debug.apk

First of all:  patching ...

```
$ objection patchapk --source app-arm-debug.apk
No architecture specified. Determining it using `adb`...
Detected target device architecture as: arm64-v8a
Using latest Github gadget version: 11.0.12
Patcher will be using Gadget version: 11.0.12
Unpacking app-arm-debug.apk
App already has android.permission.INTERNET
Reading smali from: /var/folders/4g/4rvg_s1d44v_x_6h4qmt5wwr0000gn/T/tmpp_4vlngt.apktemp/smali/sg/vp/owasp_mobile/OMTG_Android/MyActivity.smali
Injecting loadLibrary call at line: 10
Writing patched smali back to: /var/folders/4g/4rvg_s1d44v_x_6h4qmt5wwr0000gn/T/tmpp_4vlngt.apktemp/smali/sg/vp/owasp_mobile/OMTG_Android/MyActivity.smali
Creating library path: /var/folders/4g/4rvg_s1d44v_x_6h4qmt5wwr0000gn/T/tmpp_4vlngt.apktemp/lib/arm64-v8a
Copying Frida gadget to libs path...
Rebuilding the APK with the frida-gadget loaded...
Built new APK with injected loadLibrary and frida-gadget
Signing new APK.
Signed the new APK
Performing zipalign
Zipaling completed
Copying final apk from /var/folders/4g/4rvg_s1d44v_x_6h4qmt5wwr0000gn/T/tmpp_4vlngt.apktemp.aligned.objection.apk to app-arm-debug.objection.apk in current directory...
Cleaning up temp files...
```

All OK so I install it to my OnePlus on Android 8.1.0. As you can see here, the file is first not there but it appears after clicking "OMTG_DATAST_001_InternalStorage". When trying to download it it throws an error.

```
$ objection explore
...g.vp.owasp_mobile.omtg_android on (OnePlus: 8.1.0) [usb] # file download /data/user/0/sg.vp.owasp_mobile.omtg_android/files/test_file
Downloading /data/user/0/sg.vp.owasp_mobile.omtg_android/files/test_file to test_file
Unable to download file. File is not readable
...g.vp.owasp_mobile.omtg_android on (OnePlus: 8.1.0) [usb] # ls
Type    Last Modified    Read    Write    Hidden    Size    Name
------  ---------------  ------  -------  --------  ------  ------

Readable: Yes  Writable: Yes
...g.vp.owasp_mobile.omtg_android on (OnePlus: 8.1.0) [usb] # ls
Type    Last Modified            Read    Write    Hidden    Size    Name
------  -----------------------  ------  -------  --------  ------  ---------
File    2018-06-15 18:58:01 GMT  True    True     False     41.0 B  test_file

Readable: Yes  Writable: Yes
...g.vp.owasp_mobile.omtg_android on (OnePlus: 8.1.0) [usb] # file download /data/user/0/sg.vp.owasp_mobile.omtg_android/files/test_file
Downloading /data/user/0/sg.vp.owasp_mobile.omtg_android/files/test_file to test_file


An exception occurred while processing the command. If this looks like a code related error, please file a bug report!
Error: Error: VM::GetEnv failed: -2
    at e (frida/node_modules/frida-java/lib/result.js:7)
    at frida/node_modules/frida-java/lib/vm.js:71
    at a (frida/node_modules/frida-java/lib/class-factory.js:2743)
    at o (java.js:4544)
    at stringify (native)
    at frida/runtime/core.js:50
    at c (frida/runtime/message-dispatcher.js:71)
    at e (frida/runtime/message-dispatcher.js:55)
    at t (frida/runtime/message-dispatcher.js:24)
```

I've tested it in the emulator on Android: 5.1.1 and the corresponding [APK](https://github.com/OWASP/MSTG-Hacking-Playground/blob/master/Android/OMTG-Android-App/app/app-x86-debug-Android5.apk) but got the same results.

Could you please take a look at it? Thank you so much!

**Comment by leonjza** [comment]
In the directory where you perform the `ls`, can you try to just run `file download test_file` and see if that works?

**Comment by cpholguera** [comment]
I've just did it for both the phone and the emulator but got the same results :/

Here one of the outputs:

```
...g.vp.owasp_mobile.omtg_android on (OnePlus: 8.1.0) [usb] # ls
Type    Last Modified            Read    Write    Hidden    Size    Name
------  -----------------------  ------  -------  --------  ------  ---------
File    2018-06-15 20:07:18 GMT  True    True     False     41.0 B  test_file

Readable: Yes  Writable: Yes
...g.vp.owasp_mobile.omtg_android on (OnePlus: 8.1.0) [usb] # file download test_file
Downloading /data/user/0/sg.vp.owasp_mobile.omtg_android/files/test_file to test_file


An exception occurred while processing the command. If this looks like a code related error, please file a bug report!
Error: Error: VM::GetEnv failed: -2
    at e (frida/node_modules/frida-java/lib/result.js:7)
    at frida/node_modules/frida-java/lib/vm.js:71
    at a (frida/node_modules/frida-java/lib/class-factory.js:2743)
    at o (java.js:4544)
    at stringify (native)
    at frida/runtime/core.js:50
    at c (frida/runtime/message-dispatcher.js:71)
    at e (frida/runtime/message-dispatcher.js:55)
    at t (frida/runtime/message-dispatcher.js:24)
```

**Comment by leonjza** [comment]
Realize now I misread the exception part. This looks to be a Frida (or maybe device/ROM specific) thing, but I will first test with the app you linked. Thanks!

**Comment by leonjza** [comment]
Just realised I may have run into this myself today. The Android file download hook _really_ needs love, if not a port to use C functions instead as its pretty slow in its current implementation.

**Comment by cpholguera** [comment]
That would be great, it's a very handy feature. I'll keep watching and I'll be happy to re-test if there's a fix. Thanks a lot!

**Comment by dgrivera** [comment]
hi sir is this all good now or still can download file?

**Comment by leonjza** [comment]
This is being addressed in the `typescript_agent` branch which is currently a WIP. File system interactions make use of [frida-fs](https://github.com/nowsecure/frida-fs).

**Comment by dgrivera** [comment]
how to read a file if you cant download?

I use !nano or !gvim or !leafpad but still cant read the content its blank.

**Comment by dgrivera** [comment]
any update on this my good sir?

**Comment by leonjza** [comment]
I have fixed this in the `typescript_agent` branch, but it's still a while before that is released. You can try and download files using `adb pull` in the meantime though.

**Comment by hajdbo** [comment]
I tried the typescript_agent branch, but the branch looks broken.
Trying to attach returns: 
```
File "/usr/local/lib/python3.7/site-packages/objection/state/connection.py", line 80, in get_api
    raise Exception('No session available to get API')
```
or 
```
File "/usr/local/lib/python3.7/site-packages/frida/core.py", line 98, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.NotSupportedError: remote_call PTRACE_CONT wait failed: 13
```

or 

```
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.NotSupportedError: unable to find application with identifier 'Gadget'
```

**Comment by leonjza** [comment]
@hajdbo did you use the `start` instead of `explore` command perhaps? I am using this as a placeholder as I migrate to the agent, but it will revert back before release.

**Comment by leonjza** [comment]
Alright, thanks for the feedback. I am not really in a place where I can debug this now, but plan on tackling it early next year.

**Comment by dalgarins** [comment]
Hi, I have made a temporal fix, for this issue, https://github.com/sensepost/objection/pull/171
if you want to use it, while the author's objection makes the fix for this issue.

**Comment by leonjza** [comment]
Should be fixed in 1.5.0 now
